<a href="https://colab.research.google.com/github/eftekhar-hossain/SKBI_Training/blob/main/Session_7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center> <h1> <u> <font color='red'> Training on AI and ML with Python </font> </u> </h1> </center>

#Session-07: Numpy For Beginners 

> Objective: 
 1. Get familiar with Numpy Library.
 2. Learn various numpy methods
 3. Perform various operations using numpy



NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

##Using Numpy

In [ ]:
# Once you've installed NumPy you can import it as a library:

import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: 

vectors,arrays,matrices, and number generation. Let's start by discussing arrays.


**Numpy Arrays**

NumPy arrays are the main way we will use Numpy throughout the Notebook. Numpy arrays essentially come in two flavors: **vectors and matrices**. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

###Creating NumPy Arrays

From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
type(my_list)

list

In [ ]:
a = np.array(my_list)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###Built-in Methods

There are lots of built-in ways to generate Arrays

**arange**

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros and ones**

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Create an empty array with 2 elements
np.empty(2) 

array([5.43230922e-312, 7.29112202e-304])

**linspace**

Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**eye**

Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Random**

Numpy also has lots of ways to create random number arrays:

**rand**

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [ ]:
np.random.rand(2)

array([0.2016361 , 0.36774061])

In [ ]:
np.random.rand(5,5)

array([[0.21559383, 0.14568295, 0.1905823 , 0.55677055, 0.79968267],
       [0.23217003, 0.59018387, 0.40478567, 0.55400471, 0.92409927],
       [0.02347935, 0.07518721, 0.36918696, 0.21227364, 0.90995358],
       [0.22934437, 0.9560375 , 0.17837636, 0.6090272 , 0.68516905],
       [0.685776  , 0.1136489 , 0.48817432, 0.8976313 , 0.92388071]])

**randn**

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([-1.26892154, -1.46889907])

In [ ]:
np.random.randn(5,5)

array([[ 5.59731540e-01, -1.09329354e+00,  2.86272811e-01,
         9.06021764e-01,  1.21509474e+00],
       [-2.54822434e-01,  9.48845259e-01, -1.81056145e-03,
        -9.03950674e-02,  2.63949675e-03],
       [ 9.66102246e-01,  8.01592387e-01,  5.77897540e-01,
         2.72249364e-01, -1.60411819e-01],
       [-4.63341541e-01,  2.24440578e+00,  4.71785280e-02,
        -7.76326225e-01, -2.68980638e-02],
       [-1.70943929e+00,  2.76170185e-01, -2.55124406e-01,
         1.19888833e+00,  8.18637918e-01]])

**randint**

Return random integers from low (inclusive) to high (exclusive).

In [ ]:
np.random.randint(1,100)

29

In [ ]:
np.random.randint(1,100,10)

array([48,  5, 16, 41, 49, 15,  6, 51, 47, 91])

**Array Attributes and Methods**

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([28, 45, 10, 18, 11, 47,  2, 47,  2, 20])

**Reshape**

Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max,min,argmax,argmin**

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.argmax()

5

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

6

**Shape**

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
#If you start with these arrays:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

#You can concatenate them with np.concatenate().

np.concatenate((a, b))

# np.hstack
# np.vstack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

#You can concatenate them with:

np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

##Numpy Indexing and Selection

In [ ]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Bracket Indexing and Selection**

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

##Indexing a 2D array (matrices)

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

#How to convert a 1D array into a 2D array (how to add a new axis to an array)


You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [ ]:
#For example, if you start with this array:

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
(150,150)

(150,150,1)


In [ ]:
a[:, :, np.newaxis]

In [ ]:
#You can use np.newaxis to add a new axis:

a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
#You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. 
#For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

row_vector = a[np.newaxis, :]
print(row_vector.shape)

# Or, for a column vector, you can insert an axis along the second dimension:

col_vector = a[:, np.newaxis]
print(col_vector.shape)

(1, 6)
(6, 1)


In [ ]:
# You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

#For example, if you start with this array:

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

#You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
print(b.shape)

#You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
print(c.shape)

(6,)
(6, 1)
(1, 6)


How to reverse an array
```
np.flip
```

Flattening multidimensional arrays
```
np.flatten
np.ravel
```
How to get unique items and counts
```
np.unique()
```





#What Should I Use for Dot Product and Matrix Multiplication?: NumPy multiply vs. dot vs. matmul vs. @

https://mkang32.github.io/python/2020/08/30/numpy-matmul.html

#Reference


1.   [Kaggle](https://www.kaggle.com/legendadnan/numpy-tutorial-for-beginners-data-science)

2. [Numpy Docs](https://numpy.org/devdocs/user/absolute_beginners.html)
